name: storybook
description: A new Flutter project.
publish_to: none
version: 2.0.0

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  optimus:
    path: ../optimus
  storybook_flutter: ^0.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  mews_pedantic: ^0.2.1
flutter:
  uses-material-design: true
