name: mews_pedantic
description: Dart and Flutter static analysis and lint rules incorporated in Mews.
version: 0.1.3
repository: https://github.com/MewsSystems/mews-flutter

environment:
  sdk: ">=2.7.0 <3.0.0"
