name: example
description: Example.
version: 2.0.0
publish_to: none

environment:
  sdk: ">=2.10.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  optimus:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter
  mews_pedantic: ^0.2.1
